{
 "title": "Envoy Service to Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "originating_service",
    "label": "Originating Service",
    "query": "label_values(envoy_server_version, app)"
   },
   {
    "name": "destination_service",
    "label": "Destination Service",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{cluster_name=~\"inbound.*\", app=\"$originating_service\"},cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "CPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "total CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_http1_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "http CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_http2_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "http/2 CPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_active{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "active CPS"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_active{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_active{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "egress RPS"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending req to"
    },
    {
     "expr": "sum(rate(envoy_cluster_lb_healthy_panic{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "lb healthy panic RPS"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "50th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m])) by (le))",
     "legendFormat": "99th %ile"
    }
   ]
  },
  {
   "title": "4xx %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{response_code_class=\"4\",app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Success Rate (non-5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{response_code_class!=\"5\",app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Success Rate %"
    }
   ]
  },
  {
   "title": "Upstream Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_connect_timeout{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "connect timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_failure_eject{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending failure ejection"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_pending_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "pending overflow"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_timeout{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_per_try_timeout{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "per try request timeout"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_rx_reset{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request reset"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_destroy_local_with_active_rq{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "destroy initialized from originating service"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_cx_destroy_remote_active_rq{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "destroy initialized from remote service"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_maintenance_mode{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request failed maintenance mode"
    }
   ]
  },
  {
   "title": "Upstream Request Retry",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry success"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "request retry overflow"
    }
   ]
  },
  {
   "title": "Outlier Detection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_enforced_total{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Total ejections"
    },
    {
     "expr": "sum(rate(envoy_cluster_outlier_detection_ejections_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"}[1m]))",
     "legendFormat": "Total ejection overflows"
    }
   ]
  },
  {
   "title": "[[originating_service]] to [[destination_service]] connection overflow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})"
    }
   ]
  },
  {
   "title": "[[originating_service]] to [[destination_service]] request overflow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_pending_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "overflows"
    }
   ]
  },
  {
   "title": "[[originating_service]] to [[destination_service]] retry overflow",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_rq_retry_overflow{app=\"[[originating_service]]\",cluster_name=\"[[destination_service]]\"})",
     "legendFormat": "overflows"
    }
   ]
  }
 ]
}